/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-set-2019 00:27:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS public.calendario_id_seq
;

DROP SEQUENCE IF EXISTS public.chat_id_seq
;

DROP SEQUENCE IF EXISTS public.endereco_id_seq
;

DROP SEQUENCE IF EXISTS public.pessoa_id_seq
;

DROP SEQUENCE IF EXISTS public.projetos_id_seq
;

DROP SEQUENCE IF EXISTS public.usuario_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS public.Calendario CASCADE
;

DROP TABLE IF EXISTS public.Chat CASCADE
;

DROP TABLE IF EXISTS public.Endereco CASCADE
;

DROP TABLE IF EXISTS public.MeusProjetos CASCADE
;

DROP TABLE IF EXISTS public.Pessoa CASCADE
;

DROP TABLE IF EXISTS public.Projetos CASCADE
;

DROP TABLE IF EXISTS public.Usuario CASCADE
;

/* Create Tables */

CREATE TABLE public.Calendario
(
	id integer NOT NULL   DEFAULT NEXTVAL(('public."calendario_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	id_pessoa integer NOT NULL,
	data_hora_inicio date NOT NULL,
	data_hora_final date NOT NULL,
	titulo varchar(50) NOT NULL,
	descricao varchar(250) NOT NULL
)
;

CREATE TABLE public.Chat
(
	id integer NOT NULL   DEFAULT NEXTVAL(('public."chat_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	id_pessoa_destinatario integer NOT NULL,
	id_pessoa_remetente integer NOT NULL,
	data_hora_envio date NOT NULL,
	data_hora_recebimento date NULL,
	mensagem varchar(400) NOT NULL
)
;

CREATE TABLE public.Endereco
(
	id integer NOT NULL   DEFAULT NEXTVAL(('public."endereco_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	rua varchar(50) NOT NULL,
	numero integer NOT NULL,
	complemento varchar(50) NULL,
	bairro varchar(50) NOT NULL,
	cidade varchar(50) NOT NULL,
	estado varchar(2) NOT NULL,
	pais varchar(50) NOT NULL
)
;

CREATE TABLE public.MeusProjetos
(
	id_projeto integer NOT NULL,
	id_dev integer NOT NULL,
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL
)
;

CREATE TABLE public.Pessoa
(
	id integer NOT NULL   DEFAULT NEXTVAL(('public."pessoa_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	tipo_pessoa integer NOT NULL,
	nome varchar(50) NOT NULL,
	apelido varchar(50) NULL,
	email varchar(50) NOT NULL,
	telefone varchar(20) NULL,
	celular varchar(20) NOT NULL,
	facebook varchar(50) NULL,
	twitter varchar(50) NULL,
	instagram varchar(50) NULL,
	linkedin varchar(50) NULL,
	id_endereco integer NULL
)
;

CREATE TABLE public.Projetos
(
	id integer NOT NULL   DEFAULT NEXTVAL(('public."projetos_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	nome varchar(50) NOT NULL,
	id_empresa integer NOT NULL,
	palavras_chaves varchar(50) NULL,
	area_projeto varchar(50) NOT NULL,
	data_limite varchar(50) NULL,
	descricao varchar(50) NOT NULL
)
;

CREATE TABLE public.Usuario
(
	Id integer NOT NULL   DEFAULT NEXTVAL(('public."usuario_id_seq"'::text)::regclass),
	status integer NOT NULL   DEFAULT 1,
	dt_cadastro date NOT NULL,
	dt_atualizacao date NULL,
	id_pessoa integer NOT NULL,
	user_name varchar(250) NOT NULL,
	password varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.Calendario ADD CONSTRAINT PK_Calendario
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Calendario_Pessoa ON public.Calendario (id_pessoa ASC)
;

ALTER TABLE public.Chat ADD CONSTRAINT PK_Chat
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Chat_Pessoa ON public.Chat (id_pessoa_destinatario ASC)
;

CREATE INDEX IXFK_Chat_Pessoa_02 ON public.Chat (id_pessoa_remetente ASC)
;

ALTER TABLE public.Endereco ADD CONSTRAINT PK_Endereco
	PRIMARY KEY (id)
;

ALTER TABLE public.MeusProjetos ADD CONSTRAINT PK_MeusProjetos
	PRIMARY KEY (id_projeto,id_dev)
;

CREATE INDEX IXFK_MeusProjetos_Pessoa ON public.MeusProjetos (id_dev ASC)
;

CREATE INDEX IXFK_MeusProjetos_Projetos ON public.MeusProjetos (id_projeto ASC)
;

ALTER TABLE public.Pessoa ADD CONSTRAINT PK_Pessoa
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Pessoa_Endereco ON public.Pessoa (id_endereco ASC)
;

ALTER TABLE public.Projetos ADD CONSTRAINT PK_Projetos
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Projetos_Pessoa ON public.Projetos (id_empresa ASC)
;

ALTER TABLE public.Usuario ADD CONSTRAINT PK_Usuario
	PRIMARY KEY (Id)
;

ALTER TABLE public.Usuario ADD CONSTRAINT UQ_Usuario_user_name UNIQUE (user_name)
;

CREATE INDEX IXFK_Usuario_Pessoa ON public.Usuario (id_pessoa ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE public.Calendario ADD CONSTRAINT FK_Calendario_Pessoa
	FOREIGN KEY (id_pessoa) REFERENCES public.Pessoa (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.Chat ADD CONSTRAINT FK_Chat_Pessoa
	FOREIGN KEY (id_pessoa_destinatario) REFERENCES public.Pessoa (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.Chat ADD CONSTRAINT FK_Chat_Pessoa_02
	FOREIGN KEY (id_pessoa_remetente) REFERENCES public.Pessoa (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.MeusProjetos ADD CONSTRAINT FK_MeusProjetos_Pessoa
	FOREIGN KEY (id_dev) REFERENCES public.Pessoa (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.MeusProjetos ADD CONSTRAINT FK_MeusProjetos_Projetos
	FOREIGN KEY (id_projeto) REFERENCES public.Projetos (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.Pessoa ADD CONSTRAINT FK_Pessoa_Endereco
	FOREIGN KEY (id_endereco) REFERENCES public.Endereco (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.Projetos ADD CONSTRAINT FK_Projetos_Pessoa
	FOREIGN KEY (id_empresa) REFERENCES public.Pessoa (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE public.calendario_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE public.chat_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE public.endereco_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE public.pessoa_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE public.projetos_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE public.usuario_id_seq INCREMENT 1 START 1
;
